### ISSUE TITLE
Memory loss

### ISSUE THREAD

**Issue by githubaf** [bebbo/newlib-cygwin#1]
I am on ubuntu.
Incedentally I forgot -noixemul and therefore  built an image using newlib. Running it via vamos shows orphaned memory.  Compiling with -noixemul does not lead to this warning.

int main(void)
{
   printf("Hello world\n");
   return 0;
}

~/opt/m68k-amigaos_10Jun18/bin/m68k-amigaos-gcc  hello.c 
vamos a.out

Hello world
14:53:48.745  mem_alloc:WARNING:  orphan: [@0090fc +000418 009514]

**Comment by bebbo** [comment]
please test

**Comment by githubaf** [comment]
Tested with your latest commit from 4th of Dec, no memory complaints seen any more. Nice.
