### ISSUE TITLE
NULL pointer deref in malloc

### ISSUE THREAD

**Issue by watsonmw** [bebbo/newlib-cygwin#11]
Not sure this causes any crashes or anything but enforcer reports an error with this program:

```
#include <stdlib.h>
#include <stdio.h>

int main() {
    void* b = malloc(8000);
    free(b);

    return 0;
}
```

Enforcer output:

LONG-READ from 00000000                        PC: 115F6112.
USP:  1160FCFC SR: 0010 SW: 0501  (U0)(-)(-)  TCB: 114EA818.
Data: 11611948 079EC600 00001F54 00001F50 0000FFFF FFFFFFFF 0453AF49 115F4D04.
Addr: 11611948 00000000 1161194C 114D68A4 1160FD40 1160FD2C 11000830 --------.
Stck: 00000000 114E004E 114D6A50 114D6A70 1160FD40 11000830 115F54FC 114D6A80.
Stck: 00001F40 115F4F36 00001F40 1160FD40 00F9FEAA 115F4D62 00000001 114D6850.
Name: "Shell Process"  CLI: "alloc"  Hunk 0000 Offset 0000140A.

It looks like a null pointer deref access in MemMap::alloc (newlib-cygwin/newlib/libc/sys/amigaos) on the 'big' member variable:

```
 if (0 != (node->next = big->next))
```

**Comment by watsonmw** [comment]
@githubaf Ah thanks was meaning to investigate this option!  This issue doesnt happen with -noixemul.

**Comment by bebbo** [comment]
see #12

**Comment by bebbo** [comment]
please test

**Comment by watsonmw** [comment]
Thanks, looks good!
