### ISSUE TITLE
argc is always 1

### ISSUE THREAD

**Issue by githubaf** [bebbo/newlib-cygwin#2]
I am still on Ubuntu.
Usually I compile with -noixemul  and I am quite happy that.

Accidentally I forgot -noixemul and stumbled over another bug...
(Compiler etc from 14th of November)

argc is always 1
I did that in vamos but later double checked on WinUAE with the same result)

//------------------------------
#include <stdio.h>

int main(int argc, char **argv)
{
	printf("argc=%d\n",argc);
	return 0;
}
//------------------------------

~/opt/m68k-amigaos_14Nov18/bin/m68k-amigaos-gcc test.c  -o test
vamos  test 1 2 3
argc=1
12:02:05.078  mem_alloc:WARNING:  orphan: [@00a6f4 +000418 00ab0c]

Doing the same with -noixemul produces correct results.
~/opt/m68k-amigaos_14Nov18/bin/m68k-amigaos-gcc test.c  -o test -noixemul
vamos  test 1 2 3
argc=4

**Comment by bebbo** [comment]
Your finding is almost correct - and if you start it from wb argc should be 0.

newlib isn't complete yet :-)

**Comment by githubaf** [comment]
As I wrote I use usually -noixemul ans I am quite happy with that.
I just wanted to mention what I found. So absolutely no hurry from my side for this issue.

**Comment by bebbo** [comment]
please test
