### ISSUE TITLE
Compiling fails

### ISSUE THREAD

**Issue by githubaf** [bebbo/newlib-cygwin#3]
I tried to build your toolchain from yesterday, 2. Dec

=== configuring in amigaos (/home/osboxes/amiga-gcc_02Dec18/build-Linux/newlib/libm020/newlib/libc/sys/amigaos)
configure: running /bin/bash /home/osboxes/amiga-gcc_02Dec18/projects/newlib-cygwin/newlib/libc/sys/amigaos/configure --disable-option-checking '--prefix=/home/osboxes/opt/m68k-amigaos_02Dec18'  '--with-multisubdir=libm020' '--with-multisrctop=' '--enable-multilib' '--host=m68k-amigaos' 'host_alias=m68k-amigaos' 'CC=m68k-amigaos-gcc' 'CFLAGS=-Os -fomit-frame-pointer' 'CC=m68k-amigaos-gcc  -mcpu=68020' 'CXX=m68k-amigaos-g++  -mcpu=68020' 'F77= -mcpu=68020' 'GCJ= -mcpu=68020' 'GFORTRAN= -mcpu=68020' 'GOC= -mcpu=68020' --cache-file=/dev/null --srcdir=/home/osboxes/amiga-gcc_02Dec18/projects/newlib-cygwin/newlib/libc/sys/amigaos
checking whether the C++ compiler works... no
configure: error: in `/home/osboxes/amiga-gcc_02Dec18/build-Linux/newlib/libm020/newlib/libc/sys/amigaos':
configure: error: C++ compiler cannot create executables
See `config.log' for more details
configure: error: /home/osboxes/amiga-gcc_02Dec18/projects/newlib-cygwin/newlib/libc/sys/amigaos/configure failed for amigaos
configure: error: /home/osboxes/amiga-gcc_02Dec18/projects/newlib-cygwin/newlib/libc/sys/configure failed for sys
configure: error: /home/osboxes/amiga-gcc_02Dec18/projects/newlib-cygwin/newlib/libc/configure failed for libc
configure newlib...failed

**Comment by bebbo** [comment]
darn... did not test with empty prefix...

**Comment by bebbo** [comment]
fixed - please test

**Comment by githubaf** [comment]
Tested with latest commit from 4th of December, works again.
