### ISSUE TITLE
`open` does not support read/write mode with `O_TRUNC`

### ISSUE THREAD

**Issue by glebm** [bebbo/newlib-cygwin#9]
I've been debugging save file issues with the Amiga port of DevilutionX (Diablo 1), which is now upstream.

DevilutionX opens the save file in read/write mode (via C++ fstream).

The following combination of C++ flags doesn't work:

```c++
std::ios::in | std::ios::out | std::ios::binary | std::ios::trunc
```

I think the `MODE_NEWFILE` mode here *might* be the issue:

https://github.com/bebbo/newlib-cygwin/blob/e4842d83f4632adc46cc87fd814745a131299cef/newlib/libc/sys/amigaos/open.c#L13-L21

According to this source: http://www.pjhutchison.org/tutorial/file_io.html

1. `MODE_NEWFILE` is write-only
2. `MODE_READWRITE` requires an existing file

According to this other source: http://amigadev.elowar.com/read/ADCD_2.1/Includes_and_Autodocs_3._guide/node05F8.html

1. `MODE_NEWFILE` is read/write
2. `MODE_READWRITE` creates a new file if it doesn't exist

:confused:

**Comment by bebbo** [comment]
off topic: what about using `-noixemul`?

**Comment by glebm** [comment]
Let me try that and get back to you

**Comment by glebm** [comment]
Oh, looks like we're already using that 

https://github.com/diasurgical/devilutionX/blob/d1f41e4676b97405f9d08fb0dcd4c0b92ebe7a15/README.md#L235

**Comment by bebbo** [comment]
so this is a libnix issue then?

**Comment by glebm** [comment]
I don't know anything about Amiga. I hope someone from the community can help us.
Is this the libnix https://github.com/bebbo/libnix?

**Comment by glebm** [comment]
I can see in `libnix` that

fopen calls freopen:

https://github.com/bebbo/libnix/blob/2b52cda05b2c6b67f945ee63523740d3c63b59e4/sources/nix/stdio/fopen.c#L22

freopen doesn't seem to have read/write support at all:

https://github.com/bebbo/libnix/blob/2b52cda05b2c6b67f945ee63523740d3c63b59e4/sources/nix/stdio/freopen.c#L25-L38

But I don't really understand this code

**Comment by glebm** [comment]
There is also this line in `open`, not sure if it's correct:

https://github.com/bebbo/libnix/blob/2b52cda05b2c6b67f945ee63523740d3c63b59e4/sources/nix/stdio/open.c#L30

**Comment by bebbo** [comment]
don't look to deep - you might get blinded...

could you provide a minimal example? Just open stream, write, seek, read - whatever your app does?
And I try to fix it.

**Comment by glebm** [comment]
Perhaps in a few days/weeks. I'm not sure how easy a minimal example will be.

But if a non-minimal example would work for you (and you want to see Diablo running on Amiga!), it's easy to build, see Amiga via Docker here https://github.com/diasurgical/devilutionX/

Then simply try creating a few new games. It doesn't always break but a Warrior with name Test seems to do the trick for me.

**Comment by bebbo** [comment]
well, a minimal
```
#include <iostream>
#include <fstream>

int main() {
        std::fstream x("myfile.dat", std::ios::in | std::ios::out | std::ios::binary | std::ios::trunc);
        x << "foo bar\n";
        x.seekg(0, x.beg);
        x << "faa";
        x.seekg(1, x.beg);

        char c[8];
        x.read(c, 8);
        std::cout.write (c,8);

        return 0;
}
```

is working as expected

**Comment by glebm** [comment]
Here I've logged the sequence of calls that DevilutionX makes (https://github.com/diasurgical/devilutionX/pull/617):

![amiga-fail](https://user-images.githubusercontent.com/216339/74586213-460f5c80-4fdd-11ea-916a-bc8ce5524c65.png)

Note that the file does not exist at this point.

**Comment by glebm** [comment]
```c++
#include <iostream>
#include <fstream>

int main()
{
	std::fstream x("myfile.dat", std::ios::in | std::ios::out | std::ios::binary | std::ios::trunc);
	x.exceptions(std::fstream::failbit | std::fstream::badbit);
	x.seekg(0, std::ios::end);
	x.tellg();
	x.seekg(0, std::ios::end);
	x.seekp(0);
	return 0;
}
```

**Comment by glebm** [comment]
Got this after some code simplification (it's an open followed by a seek, should this actually fail?)

![amiga-bugg](https://user-images.githubusercontent.com/216339/74598696-e7de8a00-506d-11ea-9c52-2a462aa7d7cf.png)

**Comment by glebm** [comment]
Closing this issue, opened a proper one at https://github.com/bebbo/libnix/issues/30
